import type { UserAvatar } from "./types";

export interface AvatarPreset {
  id: string;
  gender: "male" | "female";
  label: string;
  description: string;
  avatar: Omit<UserAvatar, "id" | "createdAt">;
}

export const AVATAR_PRESETS: AvatarPreset[] = [
  // ===== Male 6 =====
  {
    id: "m-natural",
    gender: "male",
    label: "ナチュラル",
    description: "柔らかい雰囲気の好青年。誰からも好かれる穏やかさ。",
    avatar: {
      source: "preset",
      presetId: "m-natural",
      skinHue: 28,
      hairHue: 30,
      eyeHue: 35,
      lipHue: 10,
      outfitHueA: 210,
      outfitHueB: 220,
      parts: {
        hair: "half-up",
        eyes: "almond",
        outfit: "oversize-hoodie",
        accessory: "none",
        background: "la-sunset-blvd",
        pose: "idle",
      },
    },
  },
  {
    id: "m-cool",
    gender: "male",
    label: "クール",
    description: "鋭い目つきでミステリアス。影のあるカリスマ。",
    avatar: {
      source: "preset",
      presetId: "m-cool",
      skinHue: 22,
      hairHue: 0,
      eyeHue: 220,
      lipHue: 350,
      outfitHueA: 0,
      outfitHueB: 270,
      parts: {
        hair: "undercut",
        eyes: "sharp",
        outfit: "leather-fit",
        accessory: "cyber-visor",
        background: "dtla-neon",
        pose: "hand-on-hip",
      },
    },
  },
  {
    id: "m-idol",
    gender: "male",
    label: "アイドル",
    description: "キラキラ王子系。ステージ映えする華やかさ。",
    avatar: {
      source: "preset",
      presetId: "m-idol",
      skinHue: 25,
      hairHue: 45,
      eyeHue: 280,
      lipHue: 340,
      outfitHueA: 280,
      outfitHueB: 320,
      parts: {
        hair: "short-crop",
        eyes: "round",
        outfit: "crop-jacket",
        accessory: "hologram-earring",
        background: "hollywood-sign",
        pose: "peace-sign",
      },
    },
  },
  {
    id: "m-street",
    gender: "male",
    label: "ストリート",
    description: "ストリートカルチャー全開。LA育ちのバイブス。",
    avatar: {
      source: "preset",
      presetId: "m-street",
      skinHue: 32,
      hairHue: 50,
      eyeHue: 80,
      lipHue: 15,
      outfitHueA: 50,
      outfitHueB: 120,
      parts: {
        hair: "mohawk-fade",
        eyes: "wide",
        outfit: "streetwear",
        accessory: "neon-shades",
        background: "venice-boardwalk",
        pose: "walking",
      },
    },
  },
  {
    id: "m-adult",
    gender: "male",
    label: "おとな",
    description: "落ち着きある大人の色気。余裕のある佇まい。",
    avatar: {
      source: "preset",
      presetId: "m-adult",
      skinHue: 20,
      hairHue: 5,
      eyeHue: 160,
      lipHue: 0,
      outfitHueA: 240,
      outfitHueB: 210,
      parts: {
        hair: "short-crop",
        eyes: "droopy",
        outfit: "cyber-kimono",
        accessory: "choker-led",
        background: "rooftop-skyline",
        pose: "hand-on-hip",
      },
    },
  },
  {
    id: "m-genki",
    gender: "male",
    label: "元気",
    description: "太陽のような笑顔！エネルギー満タンの元気キャラ。",
    avatar: {
      source: "preset",
      presetId: "m-genki",
      skinHue: 35,
      hairHue: 40,
      eyeHue: 140,
      lipHue: 5,
      outfitHueA: 40,
      outfitHueB: 150,
      parts: {
        hair: "short-crop",
        eyes: "wide",
        outfit: "holo-puffer",
        accessory: "face-decal",
        background: "k-town-night",
        pose: "peace-sign",
      },
    },
  },
  // ===== Female 6 =====
  {
    id: "f-natural",
    gender: "female",
    label: "ナチュラル",
    description: "透明感のある清楚系。風になびくさらさらヘア。",
    avatar: {
      source: "preset",
      presetId: "f-natural",
      skinHue: 25,
      hairHue: 30,
      eyeHue: 30,
      lipHue: 350,
      outfitHueA: 180,
      outfitHueB: 190,
      parts: {
        hair: "long-straight",
        eyes: "almond",
        outfit: "oversize-hoodie",
        accessory: "none",
        background: "la-sunset-blvd",
        pose: "idle",
      },
    },
  },
  {
    id: "f-cool",
    gender: "female",
    label: "クール",
    description: "切れ長の目が印象的なクールビューティー。",
    avatar: {
      source: "preset",
      presetId: "f-cool",
      skinHue: 18,
      hairHue: 270,
      eyeHue: 200,
      lipHue: 340,
      outfitHueA: 260,
      outfitHueB: 300,
      parts: {
        hair: "bob",
        eyes: "cat",
        outfit: "leather-fit",
        accessory: "cyber-visor",
        background: "dtla-neon",
        pose: "hand-on-hip",
      },
    },
  },
  {
    id: "f-kawaii",
    gender: "female",
    label: "可愛い",
    description: "ピンク全開のゆめかわ系。思わず守りたくなる可愛さ。",
    avatar: {
      source: "preset",
      presetId: "f-kawaii",
      skinHue: 22,
      hairHue: 320,
      eyeHue: 300,
      lipHue: 330,
      outfitHueA: 330,
      outfitHueB: 290,
      parts: {
        hair: "twin-buns",
        eyes: "round",
        outfit: "crop-jacket",
        accessory: "halo-ring",
        background: "venice-boardwalk",
        pose: "peace-sign",
      },
    },
  },
  {
    id: "f-idol",
    gender: "female",
    label: "アイドル",
    description: "ステージ上で輝くセンター。完璧なビジュアル。",
    avatar: {
      source: "preset",
      presetId: "f-idol",
      skinHue: 25,
      hairHue: 280,
      eyeHue: 260,
      lipHue: 345,
      outfitHueA: 310,
      outfitHueB: 200,
      parts: {
        hair: "ponytail",
        eyes: "wide",
        outfit: "neon-mesh",
        accessory: "hologram-earring",
        background: "hollywood-sign",
        pose: "mic-stand",
      },
    },
  },
  {
    id: "f-street",
    gender: "female",
    label: "ストリート",
    description: "ボーイッシュでカッコいい。ダンスが似合うスタイル。",
    avatar: {
      source: "preset",
      presetId: "f-street",
      skinHue: 30,
      hairHue: 55,
      eyeHue: 90,
      lipHue: 10,
      outfitHueA: 60,
      outfitHueB: 100,
      parts: {
        hair: "half-up",
        eyes: "sharp",
        outfit: "streetwear",
        accessory: "neon-shades",
        background: "k-town-night",
        pose: "walking",
      },
    },
  },
  {
    id: "f-adult",
    gender: "female",
    label: "おとな",
    description: "エレガントで妖艶。大人の魅力が止まらない。",
    avatar: {
      source: "preset",
      presetId: "f-adult",
      skinHue: 20,
      hairHue: 10,
      eyeHue: 170,
      lipHue: 355,
      outfitHueA: 350,
      outfitHueB: 20,
      parts: {
        hair: "long-wave",
        eyes: "droopy",
        outfit: "stage-corset",
        accessory: "choker-led",
        background: "rooftop-skyline",
        pose: "hand-on-hip",
      },
    },
  },
];

export function getPreset(presetId: string): AvatarPreset | undefined {
  return AVATAR_PRESETS.find((p) => p.id === presetId);
}

export function getPresetsByGender(gender: "male" | "female"): AvatarPreset[] {
  return AVATAR_PRESETS.filter((p) => p.gender === gender);
}
